# your_script_name.spec
# Generated by PyInstaller

block_cipher = None

a = Analysis(
    ['client3.py'],
    pathex=['D:\\'],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Floppy Bird',
    debug=False,
    strip=False,
    upx=True,
    console=False,  # No console window
    icon='client3.ico',  # Optional: Add an icon
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    name='Floppy Bird',
)